"""
File: backend/auth.py
Description: Staff Authentication & Security Module.
This file provides security features for our web API. It handles receiving 
"ID Tokens" (digital hall passes) generated by Firebase when a user logs in.
It provides a 'decorator'—a special python tool that wraps around our sensitive routes
(like adding or deleting food) to ensure only valid staff members can run them.
"""
from functools import wraps
from flask import request, jsonify
from firebase_admin import auth

def verify_staff_token(req):
    """
    Function: verify_staff_token
    Purpose: Checks if the user's digital ID token inside the request is genuine.
    Auth Required: None (Internal function)
    Returns: The decoded user information from Firebase if valid, otherwise raises a system Error.
    """
    # Step 1: Pluck the 'Authorization' secret out from the incoming web headers
    auth_header = req.headers.get('Authorization')
    if not auth_header:
        # If no key was passed at all, instantly fail
        raise ValueError("Missing Authorization header")
    
    # Step 2: Ensure the key specifically uses the secure "Bearer <token>" formatting standard
    parts = auth_header.split()
    if len(parts) != 2 or parts[0].lower() != 'bearer':
        raise ValueError("Invalid Authorization header format. Expected 'Bearer <token>'")
    
    token = parts[1]
    
    # Step 3: We ask Google Firebase safely in the background: "Hey, is this a real staff token?"
    # If it is expired, forged, or garbage, this verify_id_token function will blow up and reject it!
    decoded_token = auth.verify_id_token(token)
    
    # Step 4: Return the trustworthy user details (like UID, email) so routes could use it if needed
    return decoded_token

def staff_required(f):
    """
    Decorator: @staff_required
    Purpose: A reusable wrapper we can put on top of ANY endpoint. If placed above a route,
             it acts as a bouncer. It intercepts the user traffic, checks their ID, and either 
             lets them into the route below, or kicks them out safely with a 401 error.
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        try:
            # Tell our verification function to double check the user's ID
            verify_staff_token(request)
        except Exception as e:
            # The ID was fake, missing, or expired! Block access instantly.
            return jsonify({"error": "Unauthorized"}), 401
            
        # The ID is authentic! Allow the code originally underneath the decorator to run safely.
        return f(*args, **kwargs)
        
    return decorated_function
